# 🔹 Puerto dinámico (funciona en local y en Codespaces)
server.port=${PORT:8080}

# 🔹 Conexión a PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-summer-base-acdmder2-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jhBU26pEnYyW
spring.datasource.driver-class-name=org.postgresql.Driver

# 🔹 JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# (Opcional - puedes quitarlo porque Spring lo detecta solo)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 🔹 Mejorar logs (opcional pero PRO)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE